---
settings:
  name: XCP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: NetApp XCP-Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/releasenotes.html"
  - title: Erste Schritte mit XCP
    type: solutions
    entries:
    - title: Weitere Informationen zu XCP
      url: "/xcp-index.html"
    - title: XCP-NFS-Zusatzfunktionen
      url: "/xcp-nfs-add-ons.html"
    - title: Nicht unterstützte Funktionen
      url: "/xcp-unsupported-features.html"
    - title: Unterstützte Konfigurationen
      url: "/xcp-supported-configurations.html"
    - title: Von XCP verwendete Ports
      url: "/xcp-ports-used.html"
  - title: Installieren Sie XCP
    entries:
    - title: Vorbereiten der XCP-Installation
      url: "/xcp-install-xcp.html"
    - title: Linux für XCP NFS vorbereiten
      url: "/xcp-prepare-linux-for-xcp-nfs.html"
    - title: Windows für XCP SMB vorbereiten
      url: "/xcp-prepare-windows-for-xcp-smb.html"
    - title: Dateianalyse Vorbereiten
      url: "/xcp-prepare-file-analytics.html"
    - title: Installieren Sie XCP NFS
      url: "/xcp-install-xcp-nfs.html"
    - title: Installieren Sie XCP SMB
      url: "/xcp-install-xcp-smb.html"
    - title: Installieren Sie File Analytics für NFS
      url: "/xcp-install-file-analytics-for-nfs.html"
    - title: Installieren Sie Dateianalysen für SMB
      url: "/xcp-install-file-analytics-for-smb.html"
  - title: XCP konfigurieren
    entries:
    - title: Konfigurieren Sie die INI-Datei für XCP NFS
      url: "/xcp-configure-the-ini-file-for-xcp-nfs.html"
    - title: Performance-Optimierung
      url: "/xcp-performance-tuning.html"
    - title: Umgebungsvariable
      url: "/xcp-environment-variable.html"
    - title: Konfigurieren Sie den POSIX-Anschluss
      url: "/xcp-configure-posix-connector-nfs.html"
    - title: Konfigurieren Sie den HDFS-Connector
      url: "/xcp-configure-hdfs-connector-nfs.html"
    - title: Konfiguration für horizontale Skalierung mit mehreren Nodes
      url: "/xcp-configure-multinode-scaleout-nfs.html"
    - title: Konfigurieren Sie den S3-Anschluss
      url: "/xcp-configure-s3-connector-nfs.html"
  - title: Planen Sie eine Datenmigration
    url: "/xcp-plan-data-migration.html"
    entries:
    - title: Planen Sie NFS-Datenmigration
      url: "/xcp-plan-nfs-data-migration.html"
    - title: Planen Sie die SMB-Datenmigration
      url: "/xcp-plan-smb-data-migration.html"
    - title: Planung der HDFS-Datenmigration
      url: "/xcp-plan-hdfs-data-migration.html"
    - title: Planen Sie die Verwendung von Dateianalysen
      entries:
      - title: Planen Sie Ihre Datenmigration
        url: "/xcp-file-analytics-plan-data-migration.html"
      - title: Öffnen Sie Dateianalyse
        url: "/xcp-access-file-analytics.html"
      - title: Fügen Sie Dateiserver hinzu
        url: "/xcp-add-file-servers.html"
      - title: Führen Sie einen Scan aus
        url: "/xcp-run-a-scan.html"
    - title: Filter
      url: "/xcp-filters.html"
    - title: Protokollierung für NFS und SMB (optional)
      url: "/xcp-logging-for-nfs-and-smb.html"
  - title: Datenmigration
    entries:
    - title: NFS-Daten migrieren
      url: "/xcp-migrate-data.html"
    - title: Migrieren von SMB-Daten
      url: "/xcp-migrate-smb-data.html"
      entries:
      - title: Migration alternativer NTFS-Datenstreams für SMB
        url: "/xcp-smb-ads.html"
    - title: HDFS-Daten migrieren
      url: "/xcp-migrate-hdfs-data.html"
    - title: Mehrere XCP-Jobs auf demselben Host ausführen
      url: "/xcp-run-multiple-jobs-on-same-host.html"
    - title: Zusätzliche NFS-Funktionen
      url: "/xcp-migrate-nfs-additional-features.html"
  - title: Fehlerbehebung
    entries:
    - title: Fehlerbehebung bei XCP-NFS-Fehlern
      url: "/xcp-troubleshoot-xcp-nfs.html"
    - title: Fehlerbehebung bei XCP SMB-Fehlern
      url: "/xcp-troubleshoot-xcp-smb-errors.html"
    - title: Fehler bei der XCP-Dateianalyse beheben
      url: "/xcp-troubleshoot-xcp-file-analytics-errors.html"
  - title: XCP-Referenz
    entries:
    - title: XCP-Befehlsreferenzübersicht
      url: "/xcp-reference-overview.html"
    - title: NFS-Befehlsreferenz
      entries:
      - title: Hilfe
        url: "/xcp-nfs-reference-help.html"
      - title: Anzeigen
        url: "/xcp-nfs-reference-show.html"
      - title: Lizenz
        url: "/xcp-nfs-reference-license.html"
      - title: Aktivieren
        url: "/xcp-nfs-reference-activate.html"
      - title: Scannen
        url: "/xcp-nfs-reference-scan.html"
      - title: Kopieren
        url: "/xcp-nfs-reference-copy.html"
      - title: Synchronisierung
        url: "/xcp-nfs-reference-sync.html"
      - title: Fortsetzen
        url: "/xcp-nfs-reference-resume.html"
      - title: Verifizieren
        url: "/xcp-nfs-reference-verify.html"
      - title: Chmod
        url: "/xcp-nfs-reference-chmod.html"
      - title: Chown
        url: "/xcp-nfs-reference-chown.html"
      - title: Logdump
        url: "/xcp-nfs-reference-logdump.html"
      - title: Löschen
        url: "/xcp-nfs-reference-delete.html"
      - title: Schätzung
        url: "/xcp-nfs-reference-estimate.html"
      - title: Indexlöschen
        url: "/xcp-nfs-reference-indexdelete.html"
      - title: isync
        url: "/xcp-nfs-reference-isync.html"
    - title: SMB-Befehlsreferenz
      entries:
      - title: Hilfe
        url: "/xcp-smb-reference-help.html"
      - title: Anzeigen
        url: "/xcp-smb-reference-show.html"
      - title: Lizenz
        url: "/xcp-smb-reference-license.html"
      - title: Aktivieren
        url: "/xcp-smb-reference-activate.html"
      - title: Scannen
        url: "/xcp-smb-reference-scan.html"
      - title: Kopieren
        url: "/xcp-smb-reference-copy.html"
      - title: Synchronisierung
        url: "/xcp-smb-reference-sync.html"
      - title: Verifizieren
        url: "/xcp-smb-reference-verify.html"
      - title: Konfigurieren
        url: "/xcp-smb-reference-configure.html"
      - title: Hören Sie zu
        url: "/xcp-smb-reference-listen.html"
    - title: XCP Anwendungsfälle
      entries:
      - title: XCP Anwendungsfälle
        url: "/xcp-reference-use-cases.html"
    - title: XCP-Protokollierung
      entries:
      - title: Legen Sie die Option logConfig fest
        url: "/xcp-reference-logging-logconfig.html"
      - title: Legen Sie die Ereignisprotokolloption fest
        url: "/xcp-reference-logging-eventlog.html"
      - title: Aktivieren Sie den Syslog-Client
        url: "/xcp-reference-logging-syslog.html"
    - title: XCP-Ereignisprotokolle
      entries:
      - title: NFS-Ereignisprotokolle
        url: "/xcp-reference-event-logs-nfs.html"
      - title: SMB-Ereignisprotokolle
        url: "/xcp-reference-event-logs-smb.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
