---
sidebar: sidebar 
permalink: xcp-nfs-reference-chmod.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: XCP NFS-Befehlsreferenz 
---
= Chmod
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP-NFS `chmod` Befehl scannt und ändert die Dateiberechtigung aller Dateien für die angegebene Verzeichnisstruktur. Der Befehl 'chmod' erfordert Modus oder Referenz, NFS-Freigabe oder den POSIX-Pfad als Variable. Das XCP `chmod` Befehl ändert rekursiv die Berechtigungen für einen angegebenen Pfad. In der Befehlsausgabe werden die Gesamtzahl der gescannten Dateien und die Berechtigungen angezeigt, die in der Ausgabe geändert wurden.

.Syntax
[source, cli]
----
xcp chmod -mode <value> <source NFS export path>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -mode <IP address>:/source_vol

Xcp command : xcp chmod -mode <IP address>://source_vol
Stats : 6 scanned, 4 changed mode
Speed : 1.96 KiB in (2.13 KiB/s), 812 out (882/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux] #
----
====
In der folgenden Tabelle sind die aufgeführt `chmod` Parameter und ihre Beschreibung.

[cols="2*"]
|===
| Parameter | Beschreibung 


| <<nfs_chmod_exclude,Chmod -exclude   >> | Schließt die Dateien und Verzeichnisse aus, die dem Filter entsprechen. 


| <<nfs_chmod_match,Chmod -match   >> | Verarbeitet nur die Dateien und Verzeichnisse, die dem Filter entsprechen. 


| <<nfs_chmod_reference,Chmod -reference  >> | Gibt die referenzierte Datei oder den Verzeichnispunkt an. 


| <<nfs_chmod_v,Chmod -V >> | Meldet die Ausgabe für jedes bearbeitete Objekt. 
|===


== Chmod -Exclude <filter>

Verwenden Sie die `-exclude <filter>` Parameter mit `chmod` Befehl zum Ausschließen der Dateien und Verzeichnisse, die mit dem Filter übereinstimmen.

.Syntax
[source, cli]
----
xcp chmod -exclude <filter> -mode <value> <source NFS export path>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -exclude "fnm('3.img')" -mode 770 101.11.10.10:/s_v1/D3/

Excluded: 1 excluded, 0 did not match exclude criteria
Xcp command : xcp chmod -exclude fnm('3.img') -mode 770 101.11.10.10:/s_v1/D3/
Stats : 5 scanned, 1 excluded, 5 changed mode
Speed : 2.10 KiB in (7.55 KiB/s), 976 out (3.43 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== Chmod -match <filter>

Verwenden Sie die `-match <filter>` Parameter mit `chmod` Befehl, um nur die Dateien und Verzeichnisse zu verarbeiten, die mit dem Filter übereinstimmen.

.Syntax
[source, cli]
----
xcp chmod -match <filter>  -mode <value> <source NFS export path>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -match "fnm('2.img')" -mode 777 101.11.10.10:/s_v1/D2/

Filtered: 1 matched, 5 did not match
Xcp command : xcp chmod -match fnm('2.img') -mode 101.11.10.10:/s_v1/D2/
Stats : 6 scanned, 1 matched, 2 changed mode
Speed : 1.67 KiB in (1.99 KiB/s), 484 out (578/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]
----
====


== Chmod -Reference <reference>

Verwenden Sie die `-reference <reference>` Parameter mit `chmod` Befehl zur Angabe der referenzierten Datei oder des Verzeichnispunkts.

.Syntax
[source, cli]
----
xcp chmod -reference <reference> <source NFS export path>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -reference 101.11.10.10:/s_v1/D1/1.txt 102.21.10.10:/s_v1/D2/

Xcp command : xcp chmod -reference 101.11.10.10:/s_v1/D1/1.txt 102.21.10.10:/s_v1/D2/
Stats : 6 scanned, 6 changed mode
Speed : 3.11 KiB in (3.15 KiB/s), 1.98 KiB out (2.00 KiB/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====


== Chmod -V

Verwenden Sie die `-v` Parameter mit `chmod` Befehl, um die Ausgabe für jedes bearbeitete Objekt zu melden.

.Syntax
[source, cli]
----
chmod -mode <value> -v <source NFS export path>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@user-1 linux]# ./xcp chmod -mode 111 -v file:///mnt/s_v1/D1/

mode of 'file:///mnt/s_v1/D1' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/1.txt' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/softlink_1.img' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/softlink_to_hardlink_1.img' changed from 0777 to 0111 mode
of 'file:///mnt/s_v1/D1/1.img' changed from 0777 to 0111
mode of 'file:///mnt/s_v1/D1/hardlink_1.img' changed from 0777 to 0111 mode of
'file:///mnt/s_v1/D1/1.img1' changed from 0777 to 0111
Xcp command : xcp chmod -mode 111 -v file:///mnt/s_v1/D1/ Stats : 7 scanned, 7
changed mode
Speed : 0 in (0/s), 0 out (0/s)
Total Time : 0s.
STATUS : PASSED
[root@user-1 linux]#
----
====