---
sidebar: sidebar 
permalink: xcp-smb-reference-sync.html 
keywords: netapp, xcp, reference, smb, command, commands 
summary: XCP SMB „Sync“-Befehlsreferenz 
---
= Synchronisierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der `sync` Command scannt die Quell- und Ziel-Shares parallel auf Änderungen und Änderungen und wendet die entsprechenden Aktionen auf das Ziel an, um sicherzustellen, dass das Ziel mit der Quelle identisch ist. Der `sync` Befehl vergleicht Dateninhalte, Zeitstempel, Dateiattribute, Eigentumsrechte und Sicherheitsinformationen.

.Syntax
[source, cli]
----
xcp sync \\<source SMB share> \\<IP address of SMB destination server>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====
In der folgenden Tabelle sind die aufgeführt `sync` Parameter und ihre Beschreibung.

[cols="2*"]
|===
| Parameter | Beschreibung 


| <<smb_sync_help,Sync -h, --help>> | Diese Hilfeinachricht anzeigen und beenden. 


| <<Sync -V>> | Erhöhen Sie die Fehlerverblichkeit. 


| <<smb_sync_parallel,Sync -Parallel  >> | Anzahl gleichzeitiger Prozesse (Standard: <cpu-count>). 


| <<smb_sync_match,Sync -Match  >> | Nur Dateien und Verzeichnisse verarbeiten, die dem Filter entsprechen (siehe `xcp help - match` Für Details). 


| <<smb_sync_exclude,Sync -exclude  >> | Nur Dateien und Verzeichnisse im Filter ausschließen. 


| <<Sync -preserve-atitime>> | Datum des letzten Zugriffs an der Quelle wiederherstellen. 


| <<Sync -noatitime>> | Überprüfen Sie nicht die Zeit für den Dateizugriff. 


| <<Sync -noctime>> | Prüfen Sie nicht die Erstellungszeit der Datei. 


| <<Sync -nomtime>> | Überprüfen Sie nicht die Zeit der Dateiänderung. (Diese Option ist veraltet. Die Synchronisierung wird ohne diese Option weiter ausgeführt.) 


| <<Sync -noattrs>> | Überprüfen Sie die Attribute nicht. 


| <<Sync -noOwnership>> | Überprüfen Sie die Eigentumsrechte nicht. 


| <<sync_smb_atime,Sync -atimewindow  >> | Akzeptabler Zeitunterschied für den Zugriff, in Sekunden. 


| <<sync_smb_ctime,Sync -ctimewindow  >> | Akzeptabler Zeitunterschied für die Erzeugung in Sekunden. 


| <<sync_smb_mtime,Sync -mtimewindow  >> | Akzeptable Änderung Zeitdifferenz, in Sekunden, 


| <<sync_smb_acl,Sync -acl>> | Sicherheitsinformationen kopieren. 


| <<sync_smb_acl,Sync -Fallback-user  >> | Active Directory-Benutzer oder lokaler (nicht-Domain-)Benutzer auf dem Zielcomputer, um die Berechtigungen lokaler (nicht-Domain-)Quellcomputer-Benutzer zu erhalten (Beispiel: Domain\Administrator). 


| <<sync_smb_acl,Sync -Fallback-Group  >> | Active Directory-Gruppe oder lokale (nicht-Domain-)Gruppe auf dem Zielcomputer, um die Berechtigungen lokaler (nicht-Domain-)Quellmaschinengruppen zu erhalten (Beispiel: Domain\Administratoren). 


| <<Sync -l>> | Erhöht die Ausgabedetails. 


| <<smb_sync_root,Sync -root>> | ACLs für das Stammverzeichnis synchronisieren. 


| <<smb_sync_onlyacl,Sync -onlyacl>> | Kopieren Sie nur die Sicherheitsinformationen. 


| <<smb_sync_aclverify,Sync -aclverify{yes,no} >> | Geben Sie eine Option an, um die ACL-Verifizierung während der ACL-Synchronisierung einzubeziehen oder zu überspringen. 


| <<smb_sync_bs,Sync -bs  >> | Blockgröße für Lese-/Schreibvorgänge (Standard: 1M). 


| <<Sync -ADS>> | Verwenden Sie die `sync` Befehl mit dem `-ads` Markieren, um nach Änderungen und Änderungen alternativer Datenströme in der Quell- und Ziel-SMB-Freigabe zu suchen. Wenn Änderungen vorgenommen werden, wird die Änderung auf das Ziel angewendet
Vergewissern Sie sich, dass das Ziel mit der Quelle identisch ist. 
|===


== Sync -h, --help

Verwenden Sie die `-h` Und `–-help` Parameter mit dem `sync` Befehl zum Anzeigen detaillierter Informationen über das `sync` Befehl

.Syntax
[source, cli]
----
xcp sync -–help
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp sync --help
usage: xcp sync [-h] [-v] [-parallel <n>] [-match <filter>] [-exclude <filter>] [-preserve-atime] [-noatime] [-noctime] [-nomtime] [-noattrs] [-atimewindow <float>]
[-ctimewindow <float>] [-mtimewindow <float>] [-acl] [-fallback-user FALLBACK_USER] [-fallback-group FALLBACK_GROUP] [-loglevel <name>] [-l] [-root]
[-noownership] [-onlyacl] [-aclverify {yes,no}] [-bs <n>] [-ads] source target

Note: ONTAP does not let a SMB client modify COMPRESSED or ENCRYPTED attributes. XCP sync will ignore these file attributes.

positional arguments:
   source
   target

optional arguments:
   -h, --help              show this help message and exit
   -v                      increase debug verbosity
   -parallel <n>           number of concurrent processes (default: <cpu-count>)
   -match <filter>         only process files and directories that match the filter (see `xcp help -match` for details)
   -exclude <filter>       Exclude files and directories that match the filter (see `xcp help -exclude` for details)
   -preserve-atime	       restore last accessed date on source
   -noatime                do not check file access time
   -noctime                do not check file creation time
   -nomtime                do not check file modification time
   -noattrs                do not check attributes
   -atimewindow <float>    acceptable access time difference in seconds
   -ctimewindow <float>    acceptable creation time difference in seconds
   -mtimewindow <float>    acceptable modification time difference in seconds
   -acl                    copy security information
   -fallback-user FALLBACK_USER
                           the name of the user on the target machine to receive the permissions of local (non-domain) source machine users (eg. domain\administrator)
   -fallback-group FALLBACK_GROUP
                           the name of the group on the target machine to receive the permissions of local (non-domain) source machine groups (eg. domain\administrators)
   -loglevel <name>        option to set log levelfilter
   -l                      increase output detail
   -root                   sync acl for root directory
   -noownership            do not sync ownership
   -onlyacl                sync only acls
   -aclverify {yes,no}     choose whether you need to skip acl verification
   -bs <n>                 read/write block size for sync (default: 1M)
   -ads                    sync ntfs alternate data stream
----
====


== Sync -V

Verwenden Sie die `-v` Parameter mit `sync` Befehl, um detaillierte Debug-Informationen bereitzustellen.

.Syntax
[source, cli]
----
xcp sync -v \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx\warning \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\XCP>xcp sync -v \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx\warning \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
ERROR failed to remove from target "assembly\GAC_32\Microsoft.CertificateServices.PKIClient.Cmdlets\v4.0_6.3.0.0 31bf3856ad364e35\p ki.psd1": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_tar shil\\assembly\\GAC_32\\Microsoft.CertificateServices.PKIClient.Cmdlets\\v4.0_6.3.0.0 31bf3856ad 364e35\\pki.psd1'
ERROR failed to remove from target "assembly\GAC_64\Microsoft.GroupPolicy.AdmTmplEditor\v4.0_6.3.0.0 31bf3856ad364e35\Microsoft.Gro upPolicy.AdmTmplEditor.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\10.61.
\vol_SMB_target_xxxxxx\\assembly\\GAC_64\\Microsoft.GroupPolicy.AdmTmplEditor\\v4.0_6.3.0.0 31bf 3856ad364e35\\Microsoft.GroupPolicy.AdmTmplEditor.dll'
1,933 scanned, 1,361 compared, 2 errors, 0 skipped, 0 copied, 1,120 removed, 5s ERROR failed to remove from target
"assembly\GAC_64\System.Printing\v4.0_4.0.0.0 31bf3856ad364e35\System.Printing.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_target_xxxxxx\\assembly\
4\\System.Printing\\v4.0_4.0.0.0 31bf3856ad364e35\\System.Printing.dll'
ERROR failed to remove from target "assembly\GAC_MSIL\Microsoft.PowerShell.Workflow.ServiceCore\v4.0_3.0.0.0 31bf3856ad364e35\Micro soft.PowerShell.Workflow.ServiceCore.dll": [Errno 13] Access is denied: '\\\\
\\<IP address of SMB destination server>\\vol_SMB_target_xxxxxx\\assembly\\GAC_MSIL\\Microsoft.PowerShell.Workflow.ServiceCore\\v4
.0_3.0.0.0  31bf3856ad364e35\\Microsoft.PowerShell.Workflow.ServiceCore.dll' ERROR failed to remove from target "assembly\GAC_MSIL\Microsoft.RightsManagementServices.ServerManager.DeploymentPlugin\v4.0_6.3.0.0
31bf3856ad364e35\Microsoft.RightsManagementServices.ServerManager.Deploymen n.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination
server>\\vol_SMB_target_xxxxxx\\assembly\\GAC_MSIL\\Microsoft.RightsManagementServices.ServerMana ger.DeploymentPlugin\\v4.0_6.3.0.0 31bf3856ad364e35\\Mic
.RightsManagementServices.ServerManager.DeploymentPlugin.dll'
ERROR failed to remove from target
"assembly\GAC_MSIL\Microsoft.WSMan.Management\v4.0_3.0.0.0 31bf3856ad364e35\Microsoft.WSMan.Mana gement.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_
_xxxxxx\\assembly\\GAC_MSIL\\Microsoft.WSMan.Management\\v4.0_3.0.0.0 31bf3856ad364e35\\Microsof t.WSMan.Management.dll'
ERROR failed to remove from target
"assembly\GAC_MSIL\PresentationUI\v4.0_4.0.0.0 31bf3856ad364e35\PresentationUI.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_SMB_target_xxxxxx\\assembly\
SIL\\PresentationUI\\v4.0_4.0.0.0 31bf3856ad364e35\\PresentationUI.dll'
ERROR failed to remove from target "assembly\GAC_MSIL\System.IO.Compression.FileSystem\v4.0_4.0.0.0 b77a5c561934e089\System.IO.Comp ression.FileSystem.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\10.61.71.5
_SMB_target_xxxxxx\\assembly\\GAC_MSIL\\System.IO.Compression.FileSystem\\v4.0_4.0.0.0 b77a5c561 934e089\\System.IO.Compression.FileSystem.dll'
ERROR failed to remove from target "assembly\GAC_MSIL\System.IdentityModel.Selectors\v4.0_4.0.0.0 b77a5c561934e089\System.IdentityM odel.Selectors.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\v s_target_xxxxxx\\assembly\\GAC_MSIL\\System.IdentityModel.Selectors\\v4.0_4.0.0.0 b77a5c561934e0 89\\System.IdentityModel.Selectors.dll'
2,747 scanned, 2,675 compared, 9 errors, 0 skipped, 0 copied, 2,624 removed, 10s ERROR failed to remove from target
"assembly\GAC_MSIL\System.Web.DataVisualization\v4.0_4.0.0.0 31bf3856ad364e35\System.Web.DataVis ualization.dll": [Errno 13] Access is denied: '\\\\?\\UNC\\<IP address of SMB destination server>\\vol_c
rget_xxxxxx\\assembly\\GAC_MSIL\\System.Web.DataVisualization\\v4.0_4.0.0.0 31bf3856ad364e35\\Sy stem.Web.DataVisualization.dll'
cp sync -v \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx\warning \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
2,831 scanned, 0 copied, 2,831 compared, 0 removed, 10 errors Total Time : 10s
STATUS : PASSED
----
====


== Sync - Parallel <n>

Verwenden Sie die `-parallel <n>` Parameter mit `sync` Befehl zum Festlegen einer höheren oder niedrigeren Anzahl gleichzeitiger XCP-Prozesse. Der `sync -parallel <n>` Befehl wird mit der Anzahl der gleichzeitigen Prozesse synchronisiert (Standard: <cpu-count>).


NOTE: Der Maximalwert für n ist 61.

.Syntax
[source, cli]
----
xcp sync -parallel <n>> \\<IP address or hostname of SMB server>\volxcp\\<IP address of SMB destination server>\xcp1_test1
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\xcp>xcp sync -parallel 5 \\<IP address or hostname of SMB server>\volxcp\\<IP address of SMB destination server>\xcp1_test1
658 scanned, 244 compared, 0 errors, 0 skipped, 0 copied, 0 removed, 5s
658 scanned, 606 compared, 0 errors, 0 skipped, 0 copied, 0 removed, 10s
658 scanned, 658 compared, 0 errors, 0 skipped, 0 copied, 0 removed, 10s
Sending statistics...
----
====


== Sync -Match <filter>

Verwenden Sie die `-match <filter>` Parameter mit `sync` Befehl, um den Quell- und Zielbaum zu scannen und nur die Dateien oder Verzeichnisse zu vergleichen, die mit dem Filterargument übereinstimmen. Wenn es Unterschiede gibt, wendet der Befehl die erforderlichen Aktionen auf das Ziel an, um sie synchron zu halten.

.Syntax
[source, cli]
----
xcp sync -match <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -match "'gx' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -match "'gx' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -match 'gx' in name \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 10 compared, 0 removed, 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== Sync: Schließen Sie <filter> aus

Verwenden Sie die `-exclude <filter>` Parameter mit `sync` Befehl zum Ausschließen von Dateien und Verzeichnissen im Filter.

.Syntax
[source, cli]
----
xcp sync -exclude <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp sync -exclude "path('*Exceptions*')" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -exclude path('*Exceptions*') \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
451 scanned, 427 excluded, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== Sync -preserve-atitime

Verwenden Sie die `-preserve-atime` Parameter mit `sync` Befehl zum Zurücksetzen von „atitime“ auf den ursprünglichen Wert, bevor XCP die Datei liest.

.Syntax
[source, cli]
----
xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 4s
STATUS : PASSED
----
====


== Sync -noatitime

Verwenden Sie die `-noatime` Parameter mit `sync` Befehl zum Synchronisieren aller Unterschiede in der Quelle mit dem Ziel, ausgenommen Dateien, die nur Unterschiede in der Zugriffszeit haben.

.Syntax
[source, cli]
----
xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -noatime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED

----
====


== Sync -noctime

Verwenden Sie die `-noctime` Parameter mit `sync` Befehl zum Synchronisieren aller Unterschiede in der Quelle mit dem Ziel, ausgenommen Dateien, die nur Unterschiede in der Erstellungszeit haben.

.Syntax
[source, cli]
----
xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -noctime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== Sync -nomtime

Verwenden Sie die `-nomtime` Parameter mit `sync` Befehl zum Synchronisieren aller Unterschiede in der Quelle mit dem Ziel, ausgenommen Dateien, die nur Unterschiede in der Änderungszeit haben. (Diese Option ist veraltet. Der `sync` Befehl wird ohne diese Option weiter ausgeführt.)

.Syntax
[source, cli]
----
xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -nomtime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== Sync -noattrs

Verwenden Sie die `-noattrs` Parameter mit `sync` Befehl zum Synchronisieren aller Unterschiede in der Quelle mit dem Ziel, ausgenommen Dateien, die nur Unterschiede in Dateiattributen aufweisen. XCP kopiert eine Datei nur, wenn sie über unterschiedliche Inhalte verfügt (die ACLs werden übertragen).

.Syntax
[source, cli]
----
xcp sync -noattrs \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -noattrs	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -noattrs	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -noattrs \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== Sync -noOwnership

Verwenden Sie die `-noownership` Parameter mit `sync` Befehl zum Synchronisieren aller Unterschiede zwischen der Quelle und dem Ziel, ausgenommen Dateien, die nur unterschiedliche Eigentumsverhältnisse aufweisen.

.Syntax
[source, cli]
----
xcp sync -noownership \\<IP address or hostname of SMB server>\vol_SMB_source_xxxxxx \\<IP address of SMB destination server>\vol_SMB_target_xxxxxx
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
>xcp sync -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

      Truncated Output
302,909 scanned,    301,365 compared,	0	errors,	0	skipped,	0	copied,	0	removed, 9m46s
307,632	scanned,	303,530	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 9m51s
308,434	scanned,	305,462	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 9m56s
310,824	scanned,	307,328	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m1s
313,238	scanned,	310,083	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m6s
314,867	scanned,	313,407	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m11s
318,277	scanned,	315,856	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m17s
321,005	scanned,	318,384	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m22s
322,189	scanned,	321,863	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m27s
323,906	scanned,	323,906	compared,	0	errors,	0	skipped,	0	copied,	0	removed, 10m29s

xcp sync -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
323,906 scanned, 0 copied, 323,906 compared, 0 removed, 0 errors
Total Time : 10m29s
STATUS : PASSED
----
====


== Sync -atimewindow <float>

Verwenden Sie die `-atimewindow <float>` Parameter mit `sync` Befehl zur Angabe der zulässigen Differenz in Sekunden für die atimtime einer Datei von der Quelle zum Ziel. XCP meldet Dateien nicht als unterschiedlich, wenn der Unterschied in atix kleiner als <value> ist.

.Syntax
[source, cli]
----
xcp sync -atimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
Im folgenden Beispiel akzeptiert XCP einen Zeitunterschied von bis zu 10 Minuten zwischen den Quell- und den Zieldateien und aktualisiert nicht die atimtime auf dem Ziel.

.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -atimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\source_share
xcp sync -atimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\source_share

xcp sync -atimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\source_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== Sync -ctimewindow <float>

Verwenden Sie die `-ctimewindow <float>` Parameter mit `sync` Befehl zur Angabe der zulässigen Differenz in Sekunden für die ctime einer Datei von der Quelle zum Ziel. XCP meldet Dateien nicht als unterschiedlich, wenn der Unterschied in ctime kleiner als <value> ist.

.Syntax
[source, cli]
----
xcp sync -ctimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
Im folgenden Beispiel akzeptiert XCP eine Zeitdifferenz von bis zu 10 Minuten zwischen den Quell- und den Zieldateien und aktualisiert die ctime-Datei auf dem Ziel nicht.

.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -ctimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -ctimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -ctimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== Sync -mtimewindow <float>

Verwenden Sie die `-mtimewindow <float>` Parameter mit `sync` Befehl zum Angeben der zulässigen Differenz in Sekunden für die mtime einer Datei von der Quelle zum Ziel. XCP meldet Dateien nicht als unterschiedlich, wenn der Unterschied in mtime kleiner als <value> ist.

.Syntax
[source, cli]
----
xcp sync -mtimewindow <float> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -mtimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -mtimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -mtimewindow 600 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors Total Time : 3s
STATUS : PASSED
----
====


== Sync -acl -Fallback-user <fallback_user> -Fallback-Group <fallback_group>

Verwenden Sie die `-acl`, `-fallback-user` Und `-fallback-group` Parameter mit dem `sync` Befehl zum Vergleichen der Daten und der Sicherheitsinformationen aus der Quelle mit dem Ziel und zum Anwenden der erforderlichen Aktionen auf das Ziel. Der `-fallback-user` Und `-fallback-group` Optionen sind ein Benutzer oder eine Gruppe auf dem Zielcomputer oder im Active Directory, der die Berechtigungen der lokalen (nicht-Domain-)Quellbenutzer oder -Gruppen erhält.


NOTE: Sie können das nicht verwenden `-acl` Option ohne das `-fallback-user` Und `-fallback-group` Optionen:

.Syntax
[source, cli]
----
xcp sync -acl -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\performance_SMB_home_dirs \\<IP address of SMB destination server>\performance_SMB_home_dirs
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\xcp>xcp sync -acl -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
10,796	scanned,	4,002	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	s
15,796	scanned,	8,038	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,505	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	8,707	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,730	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	8,749	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,765	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	8,786	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	8,956	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	9,320	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	0s
15,796	scanned,	9,339	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	5s
15,796	scanned,	9,363	compared,	0	errors,	0	skipped,	0	copied,	0	removed,	m0s
15,796	scanned,	10,019	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m5s
15,796	scanned,	10,042	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m10s
15,796	scanned,	10,059	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m15s
15,796	scanned,	10,075	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m20s
15,796	scanned,	10,091	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m25s
15,796	scanned,	10,108	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m30s
15,796	scanned,	10,929	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m35s
15,796	scanned,	12,443	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m40s
15,796	scanned,	13,963	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m45s
15,796	scanned,	15,488	compared,	0	errors,	0	skipped,    0	copied	0	removed,	1m50s
15,796	scanned,	15,796	compared,	0	errors,	0	skipped,     0	copied	0	removed,	1m51s

xcp sync -acl -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
15,796 scanned, 0 copied, 15,796 compared, 0 removed, 0 errors
Total Time : 1m51
STATUS : PASSED
----
====


== Sync -l

Verwenden Sie die `-l` Parameter mit `sync` Befehl zur Bereitstellung detaillierter Protokollinformationen in der Standardausgabe für alle Aktionen, die von XCP auf dem Ziel ausgeführt werden.

.Syntax
[source, cli]
----
xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

File "atime" changed, timestamps set for "agnostic"
File "atime" changed, timestamps set for "<root>"
xcp sync -l \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
634 scanned, 0 copied, 634 compared, 0 removed, 0 errors
Total Time : 3s
STATUS : PASSED
----
====


== Sync -root

Verwenden Sie die `-root` Parameter mit `sync` Befehl zum Synchronisieren der ACLs für das Stammverzeichnis.

.Syntax
[source, cli]
----
xcp sync -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\NetApp\XCP>xcp sync -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
12 scanned, 0 copied, 12 compared, 0 skipped, 0 removed, 0 errors, 1 acls copied
Total Time : 2s
STATUS : PASSED
----
====


== Sync -onlyacl-Fallback-user <fallback_user> -Fallback-Group <fallback_group>

Verwenden Sie die `-onlyacl`, `-fallback-user`, und `-fallback-group` Parameter mit dem `sync` Befehl, um die Sicherheitsinformationen zwischen der Quelle und dem Ziel zu vergleichen und die erforderlichen Aktionen auf das Ziel anzuwenden. Der `-fallback-user` Und `-fallback-group` Sind ein Benutzer oder eine Gruppe auf dem Zielcomputer oder im Active Directory, der die Berechtigungen der lokalen (nicht-Domain-)Quellbenutzer oder -Gruppen erhält.


NOTE: Sie können das nicht verwenden `-onlyacl` Parameter ohne `-fallback-user` Und `-fallback-group` Optionen:

.Syntax
[source, cli]
----
xcp sync -onlyacl -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\Users\ctladmin\Desktop>xcp sync -onlyacl -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

8,814 scanned,	0	copied,	620	compared,	0	skipped,	0	removed,	0	errors,	6s
9,294 scanned,	0	copied,	2,064	compared,	0	skipped,	0	removed,	0	errors,	11s
12,614 scanned,	0	copied,	3,729	compared,	0	skipped,	0	removed,	0	errors,	16s
13,034 scanned,	0	copied,	5,136	compared,	0	skipped,	0	removed,	0	errors,	21s
14,282 scanned,	0	copied,	7,241	compared,	0	skipped,	0	removed,	0	errors,	26s
14,282 scanned,	0	copied,	8,101	compared,	0	skipped,	0	removed,	0	errors,	31s
14,282 scanned,	0	copied,	8,801	compared,	0	skipped,	0	removed,	0	errors,	36s
14,282 scanned,	0	copied,	9,681	compared,	0	skipped,	0	removed,	0	errors,	41s
14,282 scanned,	0	copied,	10,405	compared,	0	skipped,	0	removed,	0	errors,	46s
14,282 scanned,	0	copied,	11,431	compared,	0	skipped,	0	removed,	0	errors,	51s
14,282 scanned,	0	copied,	12,471	compared,	0	skipped,	0	removed,	0	errors,	56s
14,282 scanned,	0	copied,	13,495	compared,	0	skipped,	0	removed,	0	errors,	1m1s
14,282 scanned,	0	copied,	14,282	compared,	0	skipped,	0	removed,	0	errors,	1m6s

xcp sync -onlyacl -preserve-atime -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
14,282 scanned, 0 copied, 14,282 compared, 0 skipped, 0 removed, 0 errors
Total Time : 1m7s
STATUS : PASSED

----
====


== Sync -aclverify{yes,no}

Verwenden Sie die `-aclverify{yes,no}` Parameter mit `sync` Befehl, der eine Option zum Einschließen oder überspringen der ACL-Verifizierung während der ACL-Synchronisierung bietet. Diese Option kann nur mit dem verwendet werden `sync -acl` Und `sync -onlyacl` Befehle. Die ACL-Synchronisierung führt standardmäßig eine ACL-Überprüfung durch. Wenn Sie die einstellen `-aclverify` Option auf `no`, Können Sie die ACL-Überprüfung und die überspringen `fallback-user` Und `fallback-group` Optionen sind nicht erforderlich. Wenn Sie die Einstellung festgelegt haben `-aclverify` Bis `yes`, Erfordert es die `fallback-user` Und `fallback-group` Optionen, wie im folgenden Beispiel gezeigt.

.Syntax
[source, cli]
----
xcp sync -acl -aclverify yes -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\NetApp\xcp>xcp sync -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

25 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 5s, 0 acls copied
25 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 10s, 0 acls copied
25 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 15s, 0 acls copied xcp sync -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
25 scanned, 1 copied, 25 compared, 0 skipped, 0 removed, 0 errors, 12 acls copied Total Time : 16s
STATUS : PASSED
C:\NetApp\xcp>xcp sync -acl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share

xcp sync -acl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
27 scanned, 1 copied, 27 compared, 0 skipped, 0 removed, 0 errors, 13 acls copied Total Time : 2s
STATUS : PASSED
C:\NetApp\xcp>xcp sync -onlyacl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 5s, 0 acls copied
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 10s, 0 acls copied
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 15s, 0 acls copied xcp sync -onlyacl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
C:\NetApp\xcp>xcp sync -onlyacl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
xcp sync -onlyacl -aclverify no \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
24 scanned, 0 copied, 24 compared, 0 skipped, 0 removed, 0 errors, 11 acls copied
Total Time : 2s
STATUS : PASSED
----
====


== Sync -bs <n>

Verwenden Sie die `-bs <n>` Parameter mit `sync` Befehl, um eine Lese-/Schreibblockgröße bereitzustellen. Die Standardgröße ist 1M.

.Syntax
[source, cli]
----
xcp.exe sync -bs <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp.exe sync -bs 64k \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share
1,136 scanned, 0 copied, 1,135 compared, 0 skipped, 95 removed, 0 errors, 5s
xcp.exe sync -bs 64k \\<source_IP_address>\source_share \\<IP address of SMB destination server>\dest_share 1,136 scanned, 283 copied, 1,136 compared, 0 skipped, 283 removed, 0 errors
Total Time : 10s
STATUS : PASSED
----
====


== Sync -ADS

Nutzung `-ads` Parameter mit `sync` Befehl zum Scannen nach Änderungen und Änderungen an alternativen Datenströmen in der Quell- und Ziel-SMB-Freigabe. Bei Änderungen wird die Änderung auf das Ziel angewendet, um sicherzustellen, dass das Ziel mit der Quelle identisch ist.

.Syntax
[source, cli]
----
xcp sync -ads \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp sync -ads \\<source_IP_address>\source_share\src \\<dest_IP_address>\dest_share

13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	10s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	15s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	20s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	25s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	30s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	1m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	2m50s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	2m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	3m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	3m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	4m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	4m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m5s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m10s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	5m55s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	6m0s, 1 ads copied
13	scanned,	1	copied,	12	compared,	0	skipped,	0	removed,	0	errors,	6m5s, 1 ads copied
xcp sync -ads \\<source_IP_address>\source_share\src \\<dest_IP_addess>\dest_share
13 scanned, 1 copied, 13 compared, 0 skipped, 0 removed, 0 errors, 1 ads copied
Total Time : 6m9s
STATUS : PASSED
----
====