---
sidebar: sidebar 
permalink: xcp-migrate-data.html 
keywords: netapp, xcp, migrate, data, nfs, smb, copy, resume, sync, verify 
summary: Datenmigration 
---
= NFS-Daten migrieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nach der Planung der Migration mit dem `show` Und `scan` Befehle können Sie die NFS-Daten migrieren.



== Kopieren

Der `copy` Befehl scannt und kopiert die gesamte Quellverzeichnis-Struktur zu einem Ziel-NFSv3-Export. Der `copy` Befehl erfordert, dass Quell- und Zielpfade als Variablen sind. Die gescannten und kopierten Dateien, die Durchsätze/die Geschwindigkeit und die verstrichene Zeit werden am Ende des Kopiervorgangs angezeigt.

*Beispiel:*

[listing]
----
xcp copy <source_nfs_export_path> <destination_nfs_export_path>
----
*POSIX-Pfad Beispiel:*

[listing]
----
xcp copy -newid <id> file:///mnt/source file:///mnt/dest
----
Laufen `xcp help copy` Entnehmen.



== Fortsetzen

Der `resume` Befehl startet einen zuvor unterbrochenen Kopiervorgang durch Angabe des Katalogindizes oder der Nummer neu. Der Katalogindex-Name oder die Nummer des vorherigen Kopiervorgangs wird auf dem gespeichert `<catalog path>:/catalog/indexes` Verzeichnis.

*Beispiel:*

[listing]
----
xcp resume -id <catalog_name>
----
Laufen `xcp help resume` Entnehmen.



== Synchron

Der `sync` Befehl scannt nach Änderungen und Änderungen, die an einem NFS-Quellverzeichnis mithilfe eines Katalogindex-Tag-Namens oder der Anzahl eines vorherigen Kopiervorgangs durchgeführt wurden. Inkrementelle Änderungen an der Quelle werden kopiert und auf das Zielverzeichnis angewendet. Die alten Katalogindex-Nummern werden nach dem Synchronisierungsvorgang## durch eine neue ersetzt [.underline].

*Beispiel:*

[listing]
----
xcp sync -id <catalog_name>
----
Laufen `xcp help sync` Entnehmen.



== Verifizieren

Der `verify` Befehl verwendet nach dem Kopiervorgang einen vollständigen Byte-für-Byte-Vergleich der Daten zwischen Quell- und Zielverzeichnissen ohne die Verwendung einer Katalogindiziennummer. Der Befehl überprüft auf Änderungszeiten und andere Datei- oder Verzeichnisattribute, einschließlich Berechtigungen. Der Befehl liest auch die Dateien auf beiden Seiten und vergleicht die Daten.

*Beispiel:*

[listing]
----
xcp verify <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol
----
*POSIX-Pfad Beispiel:*

[listing]
----
xcp verify file:///mnt/source file:///mnt/dest
----
Laufen `xcp help verify` Entnehmen.



== ISync

Der `isync` Befehl vergleicht die Quelle und das Ziel und synchronisiert die Unterschiede auf dem Ziel, ohne den Katalogindex zu verwenden.

*Beispiel*

[listing]
----
xcp isync <source_ip_address>:/src <destination_ip_address>:/dest

----
Verwenden Sie können `isync` Mit dem `estimate` Option zur Schätzung der Zeit, die für den benötigt wird `isync` Befehl zum Synchronisieren der inkrementellen Änderungen. Der `-id` Parameter gibt den Katalognamen eines vorherigen Kopiervorgangs an.


NOTE: Wenn Sie mehr als 25 % der verwendeten Datenset-Größe ändern, wird der angezeigt `isync estimate` Der Befehl zeigt möglicherweise nicht die erwarteten Ergebnisse an.

*Beispiel*

[listing]
----
xcp isync estimate -id <name>
----
Laufen `xcp help isync` Entnehmen.
