---
sidebar: sidebar 
permalink: xcp-nfs-reference-estimate.html 
keywords: netapp, xcp, reference, nfs, command, commands 
summary: XCP NFS-Befehlsreferenz 
---
= Schätzung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
XCP-NFS `estimate` Mit dem Befehl wird die Zeit zum Abschließen einer Basiskopie vom Quell- zum Zielspeicherort geschätzt. Es berechnet die geschätzte Zeit zum Abschließen einer Basiskopie unter Verwendung aller aktuell verfügbaren Systemressourcen, wie z. B. CPU, RAM, Netzwerk und andere Parameter. Sie können das verwenden `-target` Option zum Starten einer Beispielkopie und Abrufen der Schätzzeit.

.Syntax
[source, cli]
----
xcp estimate -id <name>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.10.10:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.10.10:/temp4' to
'10.101.10.10:/temp8'...
estimate regular file copy task completed before the 1m40s duration
0 in (0/s), 0 out (0/s), 5s
0 in (0/s), 0 out (0/s), 10s
Estimated time to copy '10.101.12.11:/temp4' to '10.101.12.10:/temp8' based on a 1m40s live test:
5.3s
Xcp command : xcp estimate -t 100 -id estimate01 -target 10.101.12.10:/temp8
Estimated Time : 5.3s
Job ID : Job_2023-04-12_08.09.16.126908_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====
In der folgenden Tabelle sind die aufgeführt `estimate` Parameter und ihre Beschreibung.

[cols="2*"]
|===
| Parameter | Beschreibung 


| <<nfs_estimate_id,Schätzung -id   >> | Gibt den Katalognamen einer vorherigen Kopie oder eines Scanindexes an. 


| <<nfs_estimate_gbit,Schätzen -gbit   >> | Verwendet Gigabits Bandbreite, um die Zeit im Idealfall zu schätzen (Standard: 1). 


| <<nfs_estimate_target,Schätzen -target   >> | Gibt das Ziel an, das für die Live-Testkopie verwendet werden soll. 


| <<nfs_estimate_t,Schätzung -t /s/m/h]>  | Gibt die Dauer der Live-Testkopie an (Standard: 5 m). 


| <<nfs_estimate_bs,Schätzung -bs [k]>  | Gibt die Lese-/Schreibblockgröße an (Standard: 64k). 


| <<nfs_estimate_dircount,Schätzung -dircount [k]>   | Gibt die Anforderungsgröße für das Lesen von Verzeichnissen an (Standard: 64k). 


| <<nfs_estimate_preserveatime,Schätzen -preserve-atitime >> | Behält die Zugriffszeit der Datei oder des Verzeichnisses bei (Standard: False). 


| <<nfs_estimate_loglevel,Schätzen -loglevel  >> | Legt die Protokollebene fest; verfügbare Ebenen sind INFO, DEBUG (Standard: INFO) 
|===


== Schätzung -id <name>

Verwenden Sie die `-id <name>` Parameter mit `estimate` Befehl zum Ausschließen der Dateien und Verzeichnisse, die mit dem Filter übereinstimmen.

.Syntax
[source, cli]
----
xcp estimate -id <name>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id csdata01

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 62.0 MiB free space.
Job ID: Job_2023-04-20_12.59.31.260914_estimate
== Best-case estimate to copy ‘data-set:/user1given 1 gigabit of bandwidth ==
112 TiB of data at max 128 MiB/s: at least 10d13h
Xcp command : xcp estimate -id csdata01
Estimated Time : 10d13h
Job ID : Job_2023-04-20_12.59.31.260914_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_12.59.31.260914_estimate.log
STATUS : PASSED
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 62.0 MiB free space.
[root@client1 linux]#
----
====


== Schätzen Sie -gbit <n>

Verwenden Sie die `-gbit <n>` Parameter mit `estimate` Befehl zur Schätzung der besten Zeit (Standard: 1). Diese Option kann nicht mit dem verwendet werden `-target` Option.

.Syntax
[source, cli]
----
xcp estimate -gbit <n> -id <name>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -gbit 10 -id estimate01

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-12_08.12.28.453735_estimate
== Best-case estimate to copy '10.101.12.11:/temp4' given 10 gigabits of bandwidth ==
0 of data at max 1.25 GiB/s: at least 0.0s
Xcp command : xcp estimate -gbit 10 -id estimate01
Estimated Time : 0.0s
Job ID : Job_2023-04-12_08.12.28.453735_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.12.28.453735_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== Schätzwert – Ziel-<path>

Verwenden Sie die `-target <path>` Parameter mit `estimate` Befehl zum Festlegen des Ziels, das für die Live-Testkopie verwendet werden soll.

.Syntax
[source, cli]
----
xcp estimate -t 100 -id <name> -target <path>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.12.11:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.12.11:/temp4' to '10.101.12.11:/temp8'...
estimate regular file copy task completed before the 1m40s duration
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== Schätzung -t <n[s|m|h]>

Verwenden Sie die `-t <n[s|m|h]>` Parameter mit `estimate` Befehl zum Festlegen der Dauer der Live-Testkopie. Der Standardwert ist 5m.

.Syntax
[source, cli]
----
xcp estimate -t <n[s|m|h]> -id <name> -target <path>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@client-01 linux]# ./xcp estimate -t 100 -id estimate01 -target 10.101.12.12:/temp8

xcp: WARNING: your license will expire in less than 10 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-12_08.09.16.126908_estimate
Starting live test for 1m40s to estimate time to copy '10.101.12.11:/temp4' to
'10.101.12.12:/temp8'...
estimate regular file copy task completed before the 1m40s duration
0 in (0/s), 0 out (0/s), 5s
0 in (0/s), 0 out (0/s), 10s
Estimated time to copy '10.101.12.11:/temp4' to '10.101.12.12:/temp8' based on a 1m40s live
test: 5.3s

Xcp command : xcp estimate -t 100 -id estimate01 -target 10.101.12.11:/temp8
Estimated Time : 5.3s
Job ID : Job_2023-04-12_08.09.16.126908_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-12_08.09.16.126908_estimate.log
STATUS : PASSED
[root@client-01linux]#
----
====


== Schätzung - bs <n[k]>

Verwenden Sie die `-bs <n[k]>` Parameter mit `estimate` Befehl zum Angeben der Lese-/Schreibblockgröße. Der Standardwert ist 64k.

.Syntax
[source, cli]
----
xcp estimate -id <name> -bs <n[k]>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id estimate01 -bs 128k

xcp: WARNING: your license will expire in less than 7 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-24_08.44.12.564441_estimate
63.2 KiB in (12.5 KiB/s), 2.38 KiB out (484/s), 5s
== Best-case estimate to copy 'xxx' given 1 gigabit of bandwidth ==
112 TiB of data at max 128 MiB/s: at least 10d13h
Xcp command : xcp estimate -id estimate01 -bs 128k
Estimated Time : 10d13h
Job ID : Job_2023-04-24_08.44.12.564441_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-24_08.44.12.564441_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== Schätzen Sie -dircount <n[k]>

Verwenden Sie die `-dircount <n[k]>` Parameter mit `estimate` Befehl zum Angeben der angeforderten Größe für das Lesen von Verzeichnissen. Der Standardwert ist 64k.

.Syntax
[source, cli]
----
xcp estimate -id <name> -dircount <n[k]> -t <n> -target <path>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -id csdata01 -dircount 128k -t 300 -target <path>

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 61.6 MiB free space.
Job ID: Job_2023-04-20_13.03.46.820673_estimate
Starting live test for 5m0s to estimate time to copy ‘data-set:/user1 to `<path>`...
1,909 scanned, 126 copied, 2 giants, 580 MiB in (115 MiB/s), 451 MiB out (89.5 MiB/s), 5s
1,909 scanned, 134 copied, 2 giants, 1.23 GiB in (136 MiB/s), 1015 MiB out (112 MiB/s), 10s
1,909 scanned, 143 copied, 2 giants, 1.88 GiB in (131 MiB/s), 1.54 GiB out (113 MiB/s), 15s
.
.
.
7,136 scanned, 2,140 copied, 4 linked, 8 giants, 33.6 GiB in (110 MiB/s), 32.4 GiB out (110
MiB/s), 4m57s
Sample test copy completed for, 300.03s
0 in (-7215675436.180/s), 0 out (-6951487617.036/s), 5m2s
2,186 scanned, 610 KiB in (121 KiB/s), 76.9 KiB out (15.3 KiB/s), 5m7s
Estimated time to copy ‘data-set:/user1to '10.01.12.11:/mapr11' based on a 5m0s live test:
7d6h
Xcp command : xcp estimate -id csdata01 -dircount 128k -t 300 -target 10.101.12.11:/mapr11
Estimated Time : 7d6h
Job ID : Job_2023-04-20_13.03.46.820673_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_13.03.46.820673_estimate.log
STATUS : PASSED
xcp: WARNING: XCP catalog volume is low on disk space: 99.99% used, 61.6 MiB free space.
[root@client1 linux]#
----
====


== Schätzung - Parallel <n>

Verwenden Sie die `-parallel <n>` Parameter mit `estimate` Befehl zur Angabe der maximalen Anzahl gleichzeitiger Batch-Prozesse. Der Standardwert ist 7.

.Syntax
[source, cli]
----
xcp estimate -loglevel <name> -parallel <n> -id <name>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -loglevel DEBUG -parallel 8 -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.36.45.535209_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth ==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -parallel 8 -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.36.45.535209_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.36.45.535209_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== Schätzen -preserve-atitime

Verwenden Sie die `-preserve-atime` Parameter mit `estimate` Befehl, um die Zugriffszeit der Datei oder des Verzeichnisses beizubehalten. Der Standardwert ist false.

.Syntax
[source, cli]
----
xcp estimate -loglevel <name> -preserve-atime -id <name>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
root@client1 linux]# ./xcp estimate -loglevel DEBUG -preserve-atime -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.19.04.050516_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth
==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -preserve-atime -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.19.04.050516_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.19.04.050516_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====


== Schätzen Sie -loglevel <name>

Verwenden Sie die `-loglevel <name>` Parameter mit `estimate` Befehl zum Festlegen der Protokollebene; verfügbare Ebenen sind INFO und DEBUG. Die Standardebene ist INFO.

.Syntax
[source, cli]
----
xcp estimate -loglevel <name> -id <name>
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
[root@client1 linux]# ./xcp estimate -loglevel DEBUG -parallel 8 -id estimate1

xcp: WARNING: your license will expire in less than 11 days! You can renew your license at
https://xcp.netapp.com
Job ID: Job_2023-04-20_11.36.45.535209_estimate
== Best-case estimate to copy '10.10.101.10:/users009/xxx/mnt' given 1 gigabit of bandwidth ==
6.75 GiB of data at max 128 MiB/s: at least 54.0s
Xcp command : xcp estimate -loglevel DEBUG -parallel 8 -id estimate1
Estimated Time : 54.0s
Job ID : Job_2023-04-20_11.36.45.535209_estimate
Log Path : /opt/NetApp/xFiles/xcp/xcplogs/Job_2023-04-20_11.36.45.535209_estimate.log
STATUS : PASSED
[root@client1 linux]#
----
====