---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-smb.html 
keywords: netapp, xcp, install, installing, file, analytics, smb, upgrade, upgrading 
summary: Dateianalyse für SMB installieren oder aktualisieren 
---
= Installieren Sie Dateianalysen für SMB
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dateianalyse für SMB installieren oder aktualisieren

.Über diese Aufgabe
Die Systemanforderungen für SMB finden Sie unter link:xcp-install-xcp-smb.html["Installieren Sie XCP SMB"].

.Bevor Sie beginnen
* Sie müssen XCP-Dateianalysen für NFS auf einem Linux-Rechner konfigurieren, um den XCP-SMB-Dienst verwenden zu können.
* Stellen Sie sicher, dass der XCP-Dienst auf Ihrem Linux-Computer ausgeführt wird, bevor Sie mit der Konfiguration von XCP-Dateianalysen auf einem Windows-Rechner beginnen.




== Neue Installation von Dateianalysen für SMB

Führen Sie die folgenden Schritte aus, um eine Neuinstallation von Dateianalysen für SMB durchzuführen.

.Schritte
. Kopieren Sie die `xcp.exe` Datei auf Ihre Windows `C:` Laufwerk, dieser Binär ist im Inneren verfügbar `/xcp/windows` Nachdem Sie die enttar `tgz` Datei:
. Laden Sie die XCP-Lizenzdatei vom herunter link:https://xcp.netapp.com/["XCP-Standort"^].
. Erstellen Sie den Ordner `C:\\NetApp\XCP` Und kopieren Sie die XCP-Lizenz an diesen Speicherort.
. Aktivieren Sie die XCP-Lizenz mit dem folgenden Befehl an der Eingabeaufforderung:  `xcp.exe activate`
. Führen Sie in der Windows-CLI-Eingabeaufforderung den Befehl aus `xcp configure`.
. Geben Sie bei entsprechender Aufforderung die IP-Adresse des Linux-Rechners ein, auf dem der XCP-Dateianalyseserver konfiguriert ist.
. Kopieren Sie die `server.key` Und `server.crt` Dateien von `/opt/NetApp/xFiles/xcp/` (Im Linux-Feld, in dem XCP-Dateianalyse bereits konfiguriert ist) zu `C:\NetApp\XCP`.
+
Wenn Sie über ein Zertifizierungsstellenzertifikat verfügen, legen Sie das Zertifikat optional in ein `C:\NetApp\XCP` Mit dem gleichen Namen und den gleichen Erweiterungen.

. Gehen Sie zu Ihrem Windows-Rechner und starten Sie `xcp listen`, Jetzt ist XCP File Analytics für SMB konfiguriert. Halten Sie das Fenster offen, um den Dienst kontinuierlich auszuführen.
. Starten Sie die Dateianalyse in einem unterstützten Browser: `\https://<ip address of linux>/xcp`
+
Siehe link:xcp-install-xcp-smb.html["Installieren Sie XCP SMB"] Für Informationen zu unterstützten Browsern.

. Wählen Sie `OK` Wenn das Dialogfeld angezeigt wird.
+

NOTE: Eine neue Registerkarte wird geöffnet. Aktivieren Sie Pop-ups im Browser, wenn sie blockiert sind.

. Akzeptieren Sie die Datenschutzrichtlinie für die URL. Die folgende Meldung wird angezeigt: `SMB agent is ready to use. Please refresh the analytics page`
. Zeigen Sie den SMB-Agent unter der Agentenkarte an, indem Sie zur ursprünglichen Registerkarte zurückkehren, auf der die XCP-Dateianalyse-GUI gehostet wird, und die Seite aktualisieren.




== Upgrade von Dateianalysen für SMB

Führen Sie die folgenden Schritte aus, um die vorhandene Dateianalyse für SMB zu aktualisieren.

. Überprüfen Sie vor dem Ausführen von File Analytics, ob der Linux-Server, auf dem File Analytics ausgeführt wird, ebenfalls aktualisiert wurde und der Dienst ausgeführt wird.
. Stoppen Sie unter Windows den vorhandenen XCP-Dienst, indem Sie eingeben `CTRL-C` In der Kommandozeile.
. Austausch `xcp.exe` Mit der neuesten Binärdatei.
. Gehen Sie zu Ihrem Windows-Rechner und starten Sie `xcp listen` Konfigurieren von XCP File Analytics für SMB. Halten Sie das Fenster offen, um den Dienst kontinuierlich auszuführen.
. Starten Sie die Dateianalyse in einem unterstützten Browser: `\https://<ip address of linux>/xcp`
+
Siehe link:xcp-install-xcp-smb.html["Installieren Sie XCP SMB"] Für Informationen zu unterstützten Browsern.

. Wählen Sie *OK*, wenn das Dialogfeld angezeigt wird.
+

NOTE: Eine neue Registerkarte wird geöffnet. Aktivieren Sie Pop-ups im Browser, wenn sie blockiert sind.

. Akzeptieren Sie die Datenschutzrichtlinie für die URL. Die folgende Meldung wird angezeigt: `SMB agent is ready to use. Please refresh the analytics page`
. Zeigen Sie den SMB-Agent unter der Agentenkarte an, indem Sie zur ursprünglichen Registerkarte zurückkehren, auf der die XCP-Dateianalyse-GUI gehostet wird, und die Seite aktualisieren.

