---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-nfs.html 
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading 
summary: Installation oder Upgrade der Dateianalyse für NFS 
---
= Installieren Sie File Analytics für NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Installation oder Upgrade der Dateianalyse für NFS

.Über diese Aufgabe
Informationen zu den Systemanforderungen für NFS finden Sie unter link:xcp-install-xcp-nfs.html["Installieren Sie XCP NFS"].

Der `configure.sh` Script installiert XCP File Analytics auf einem Red hat Enterprise Linux (RHEL)-Hostcomputer. Im Rahmen der Installation installiert das Skript Postgres Database, Apache HTTPD Server und andere erforderliche Pakete auf dem Host-Linux-Rechner. Informationen zu bestimmten unterstützten RHEL-Versionen finden Sie im link:https://mysupport.netapp.com/matrix/["IMT"^]. Sie können je nach Bedarf eine aktuellere Version ändern oder aktualisieren und die Sicherheitsrichtlinien einhalten. Um mehr über die zu erfahren `configure.sh` Skript, Ausführen `./configure.sh -h` In der Kommandozeile.

.Bevor Sie beginnen
* Wenn XCP-Vorgänge ausgeführt werden, empfiehlt NetApp, die Vorgänge vor dem Start der Konfiguration abzuschließen.
* Ihr Linux-Rechner muss mit dem Yum-Repository-Server oder dem Internet verbunden sein.
* Wenn auf dem Linux-Rechner eine Firewall konfiguriert ist, müssen Sie die Firewall-Einstellungen so ändern, dass Port 5030 aktiviert wird, der vom XCP-Dienst verwendet wird.


.Schritte
. Installation oder Upgrade der Dateianalyse für NFS
+
[role="tabbed-block"]
====
.Installieren Sie File Analytics
--
.. Navigieren Sie zum `xcp` Und führen Sie die aus `./configure.sh` Skript:
+
Wenn die Installation erfolgreich war, wird die folgende Meldung angezeigt:

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----
+

NOTE: Sie können diesen Benutzernamen und dieses Kennwort verwenden, um sich bei der GUI von File Analytics anzumelden.



--
.Aktualisieren Sie Dateianalyse
--
.. Navigieren Sie zum `xcp` Ordner und Ausführen `./configure.sh -f`.
.. Geben Sie an der Eingabeaufforderung ein `y` Um das System zu bereinigen und neu zu konfigurieren.
+
Nachdem das Skript genehmigt wurde, bereinigt es die vorhandene Konfiguration und konfiguriert das System neu.

+
Wenn erfolgreich, wird die folgende Meldung angezeigt:

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----


--
====
. Starten Sie die Dateianalyse in einem unterstützten Browser: *\https://<ip-Adresse von linux>/xcp*.
+
Siehe link:xcp-install-xcp-nfs.html["Installieren Sie XCP NFS"] Für Informationen zu unterstützten Browsern.


