---
sidebar: sidebar 
permalink: xcp-smb-reference-copy.html 
keywords: netapp, xcp, reference, smb, command, commands 
summary: XCP SMB „copy“-Befehlsreferenz 
---
= Kopieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der `copy` Befehl scannt die gesamte Quellverzeichnis-Struktur und kopiert sie auf eine SMB-Zielfreigabe. Der `copy` Für den Befehl sind Quell- und Zielpfade als Variablen erforderlich. Die gescannten und kopierten Dateien, Durchsatz/Geschwindigkeit und Details der verstrichenen Zeit werden alle fünf Sekunden auf die Konsole gedruckt.

[NOTE]
====
* Die Laufzeitprotokolldatei ist unter „C:\NetApp\XCP“ gespeichert.
* Das `copy` Mit Befehl werden Daten ohne Zugriffssteuerungsliste (Access Control List, ACL) kopiert.


====
.Syntax
[source, cli]
----
xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0 errors
Total Time : 2s
STATUS : PASSED
----
====
In der folgenden Tabelle sind die aufgeführt `copy` Parameter und ihre Beschreibung.

[cols="2*"]
|===
| Parameter | Beschreibung 


| <<smb_copy_help,Copy -h, --help>> | Zeigt detaillierte Informationen zum an `copy` Befehl. 


| <<Kopie -V>> | Erhöhen Sie die Fehlerverblichkeit. 


| <<smb_copy_parallel,Kopieren -parallel  >> | Gibt die Anzahl der gleichzeitigen Prozesse an (Standard: <cpu-count>). 


| <<smb_copy_match,Copy -Match  >> | Verarbeitet nur Dateien und Verzeichnisse, die dem Filter entsprechen (siehe `xcp help - match` Für Details). 


| <<smb_copy_exclude,Kopieren -exclude  >> | Schließt nur Dateien und Verzeichnisse im Filter aus 


| <<Copy -preserve-atitime>> | Stellt das Datum des letzten Zugriffs auf die Quelle wieder her. 


| <<smb_copy_acl,Copy -acl>> | Kopiert Sicherheitsinformationen. 


| <<smb_copy_acl,Copy -Fallback-user  >> | Gibt den Active Directory-Benutzer oder lokalen (nicht-Domain-)Benutzer auf dem Zielcomputer an, der die Berechtigungen lokaler (nicht-Domain-)Quellcomputer-Benutzer erhält. Beispiel: Domäne\Administrator. 


| <<smb_copy_acl,Copy -Fallback-Group  >> | Gibt die Active Directory-Gruppe oder lokale (nicht-Domain-)Gruppe auf dem Zielcomputer an, der die Berechtigungen lokaler (nicht-Domain-)Quellmaschinengruppen erhält. Beispiel: Domain\Administratoren. 


| <<smb_copy_root,Copy -root>> | Kopiert die ACLs für ein Stammverzeichnis. 


| <<smb_copy_aclverify,Copy -aclverify {yes,no}>> | Bietet eine Option zum überspringen oder Einschließen der acl-Überprüfung während des Kopiervorgangs -acl. 


| <<Copy -noOwnership>> | Kopiert keine Eigentumsrechte. 


| <<smb_copy_bs,Kopieren -bs  >> | Blockgröße für Lese-/Schreibvorgänge (Standard: 1M) 


| <<Copy -ADS>> | Kopiert alternative NTFS-Datenströme von der Quell-SMB-Freigabe auf die Ziel-SMB-Freigabe. 
|===


== Copy -h, --help

Verwenden Sie die `-h` Und `–-help` Parameter mit dem `copy` Befehl zum Anzeigen detaillierter Informationen über das `copy` Befehl

.Syntax
[source, cli]
----
xcp copy –help
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp copy –help

usage: xcp copy [-h] [-v] [-parallel <n>] [-match <filter>] [-exclude <filter>] [-preserve- atime] [-acl] [-fallback-user FALLBACK_USER]
[-fallback-group FALLBACK_GROUP] [-loglevel <name>] [-root] [-noownership] [- aclverify {yes,no}] [-bs <n>] [-ads]
         source target

positional arguments:
   source
   target

optional arguments:
-h, --help            show this help message and exit
-v                    increase debug verbosity
-parallel <n>         number of concurrent processes (default: <cpu-count>)
-match <filter>       only process files and directories that match the filter (see `xcp help -match` for details)
-exclude <filter>     Exclude files and directories that match the filter (see `xcp help - exclude` for details)
-preserve-atime       restore last accessed date on source
-acl                  copy security information
-fallback-user FALLBACK_USER
                      the name of the user on the target machine to receive the permissions of local (non-domain) source machine users (eg. domain\administrator)
-fallback-group FALLBACK_GROUP
                      the name of the group on the target machine to receive the permissions of local (non-domain) source machine groups (eg. domain\administrators)
-loglevel <name>      option to set log level filter (default:INFO)
-root                 copy acl for root directory
-noownership          do not copy ownership
-aclverify {yes,no}   choose whether you need to skip acl verification
-bs <n>               read/write block size for copy (default: 1M)
-ads                  copy NTFS alternate data streams.
----
====


== Kopie -V

Verwenden Sie die `-v` Parameter mit `copy` Befehl, um detaillierte Debug-Informationen bereitzustellen.

.Syntax
[source, cli]
----
xcp copy -v \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -v \\<IP address of SMB destination server>\src \\<IP address of SMB destination server>\dest\d1

failed to set attributes for "d1": (5, 'CreateDirectory', 'Access is denied.')
failed to copy "f1.txt": (5, 'CreateFile', 'Access is denied.')
failed to set attributes for "": (5, 'SetFileAttributesW', 'Access is denied.') error setting timestamps on "": errno (code: 5) Access is denied.
H:\p 4\xcp_latest\xcp_cifs\xcp\ main .py copy -v \\<IP address of SMB destination server>\src \\<IP address of SMB destination server>\dest\d1
3 scanned, 0 matched, 0 skipped, 1 copied, 0 (0/s), 3 errors
Total Time : 3s
STATUS : FAILED
----
====


== Copy: Paralleles <n>

Verwenden Sie die `-parallel <n>` Parameter mit `copy` Befehl zum Festlegen einer höheren oder niedrigeren Anzahl gleichzeitiger XCP-Prozesse. Der Standardwert für `-parallel` Ist gleich der CPU-Anzahl.


NOTE: Der Maximalwert für n ist 61.

.Syntax
[source, cli]
----
xcp copy -parallel <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -parallel 7	\\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -parallel 7 \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0errors
Total Time : 2s
STATUS : PASSED
----
====


== Copy -Match <filter>

Verwenden Sie die `-match <filter>` Parameter mit `copy` Befehl, um nur die Daten zu kopieren, die mit dem übergebenen Argument übereinstimmen.

.Syntax
[source, cli]
----
xcp copy -match <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -match "'gx' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -match 'gx' in name \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 5 matched, 4 copied, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


== Copy: Schließt <filter> aus

Verwenden Sie die `-exclude <filter>` Parameter mit `copy` Befehl zum Kopieren nur ausgeschlossener Daten.

.Syntax
[source, cli]
----
xcp copy -exclude <filter> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
Im folgenden Beispiel wurden die Dateien und Verzeichnisse, die den String "Resync" in ihrem Namen haben, für die Kopie ausgeschlossen.

.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -exclude "'resync' in name" \\<IP address or hostname of SMB server>\source_share \\<IP address or hostname of SMB server>\dest_share


xcp copy -exclude 'resync' in name \\<IP address or hostname of SMB server>\source_share \\\\<IP address or hostname of SMB server>\dest_share
18 scanned, 2 excluded, 0 skipped, 15 copied, 122KiB (50.5KiB/s), 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== Copy -preserve-atitime

Verwenden Sie die `-preserve-atime` Parameter mit `copy` Befehl zum Zurücksetzen des „atitime“ auf den ursprünglichen Wert, bevor XCP die Datei liest.

.Syntax
[source, cli]
----
xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -preserve-atime \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
317 scanned, 0 matched, 316 copied, 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== Copy -acl -Fallback-user <fallback_user> -Fallback-Group <fallback_group>

Verwenden Sie die `-acl` Parameter mit `copy` Befehl zum Aktivieren der Übertragung der Sicherheitsdeskriptoren (ACLs).

Verwenden Sie die `-acl` Parameter mit `-fallback-user` Und `-fallback-group` Optionen zum Festlegen eines Benutzers und einer Gruppe auf dem Zielcomputer oder von Active Directory zum Empfangen der Berechtigungen von lokalen (nicht-domänenübergreifenden) Benutzern oder Gruppen des Quellcomparters. Dies bezieht sich nicht auf nicht übereinstimmenden Benutzer aus einem Active Directory.

.Syntax
[source, cli]
----
xcp copy -acl -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----


== Copy -aclverify {yes,no}

Verwenden Sie die `-aclverify {yes,no}` Parameter mit `copy` Befehl, um eine Option zum überspringen oder Einschließen der ACL-Überprüfung während eines ACL-Kopiervorgangs bereitzustellen.

Sie müssen den verwenden `-aclverify {yes,no}` Parameter mit `copy -acl` Befehl. Standardmäßig werden die ACL-Kopiervorgang die ACLs überprüft. Wenn Sie die einstellen `-aclverify` Option auf `no`, Können Sie die ACL-Überprüfung und die überspringen `fallback-user` Und `fallback-group` Optionen sind nicht erforderlich. Wenn Sie die Einstellung festgelegt haben `-aclverify` Bis `yes`, Erfordert es die `fallback-user` Und `fallback-group` Optionen, wie im folgenden Beispiel gezeigt.

.Syntax
[source, cli]
----
xcp copy -acl -aclverify yes -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\NetApp\xcp>xcp copy -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group"
\\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 5s, 0 acls copied
12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 10s, 0 acls copied
12 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 15s, 0 acls copied xcp copy -acl -aclverify yes -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
12 scanned, 0 matched, 0 skipped, 11 copied, 10KiB (634/s), 0 errors, 11 acls copied
Total Time : 16s
STATUS : PASSED

C:\NetApp\xcp>xcp copy -acl -aclverify no \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

xcp copy -acl -aclverify no \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
12 scanned, 0 matched, 0 skipped, 11 copied, 10KiB (5.61KiB/s), 0 errors, 11 acls copied
Total Time : 1s
STATUS : PASSED
----
====


== Copy -root

Verwenden Sie die `-root` Parameter mit `copy` Befehl zum Kopieren der ACLs für das Stammverzeichnis.

.Syntax
[source, cli]
----
xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\NetApp\XCP>xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share

xcp copy -acl -root -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
6 scanned, 0 matched, 0 skipped, 5 copied, 200 (108/s), 0 errors, 6 acls copied
Total Time : 1s
STATUS : PASSED
----
====


== Copy -noOwnership

Verwenden Sie die `-noownership` Parameter mit `copy` Befehl, um anzugeben, dass die Eigentumsrechte nicht von der Quelle auf das Ziel kopiert werden sollen. Sie müssen verwenden `-noownership` Mit dem `-acl` Option und erfordert es `fallback-user` Und `fallback-group` Als obligatorische Parameter.

.Syntax
[source, cli]
----
xcp.exe copy -acl -noownership -fallback-user <fallback_user> -fallback-group <fallback_group> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
C:\Netapp\xcp>xcp.exe copy -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

568 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 5s, 0 acls copied
568 scanned, 0 matched, 0 skipped, 0 copied, 0 (0/s), 0 errors, 10s, 0 acls copied
568 scanned, 0 matched, 0 skipped, 135 copied, 4.26MiB (872KiB/s), 0 errors, 15s, 137 acls copied xcp.exe copy -acl -noownership -fallback-user "DOMAIN\User" -fallback-group "DOMAIN\Group" \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
568 scanned, 0 matched, 0 skipped, 567 copied, 17.7MiB (1.01MiB/s), 0 errors, 567 acls copied
Total Time : 17s
STATUS : PASSED
----
====


== Copy -bs <n>

Verwenden Sie die `-bs <n>` Parameter mit `copy` Befehl, um eine Lese-/Schreibblockgröße bereitzustellen. Der Standardwert ist 1M.

.Syntax
[source, cli]
----
xcp.exe copy -bs <n> \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\Netapp\xcp>xcp.exe copy -bs 32k \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share

xcp.exe copy -bs 32k \\<source_IP_address>\source_share \\<destination_IP_address>\dest_share
568 scanned, 0 matched, 0 skipped, 567 copied, 17.7MiB (6.75MiB/s), 0 errors
Total Time : 2s
STATUS : PASSED
----
====


== Copy -ADS

Verwenden Sie die `-ads` Parameter mit `copy` Befehl zum Kopieren alternativer NTFS-Datenströme von der Quell-SMB-Freigabe auf die Ziel-SMB-Freigabe.

.Syntax
[source, cli]
----
xcp copy -ads \\<IP address or hostname of SMB server>\source_share \\<IP address of SMB destination server>\dest_share
----
.Beispiel anzeigen
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp copy -ads \\<source_IP_address>\source_share\src \\<dest_IP_address>\dest_share

6   scanned, 0 matched, 0 skipped, 3 copied, 13 (2.41/s), 0 errors, 5s, 10 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	10s, 11 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	15s, 12 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	20s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	25s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	30s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	35s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	40s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	45s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	2m15s, 13 ads copied
6	scanned,	0	matched,	0	skipped,	3	copied,	13	(0/s),	0	errors,	3m5s, 13 ads copied
xcp copy -ads \\<source_IP_address>\source_share\src \\<desination_IP_address>\dest_share
6 scanned, 0 matched, 0 skipped, 5 copied, 26 (0.137/s), 0 errors, 14 ads copied
Total Time : 3m9s
STATUS : PASSED
----
====