---
sidebar: sidebar 
permalink: xcp-run-multiple-jobs-on-same-host.html 
keywords: xcp, configure, nfs, posix, connector 
summary: Der POSIX-Anschluss ermöglicht XCP den Zugriff auf alle Linux-gemounteten Filesysteme, z. B. NFSv4, XFS und Veritas. 
---
= Mehrere XCP-Jobs auf demselben XCP-Host ausführen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ab XCP 1.9.2 können Sie mehrere XCP-Jobs oder -Befehle auf einem einzelnen XCP-Host ausführen, vorausgesetzt, der Host verfügt über ausreichende Ressourcen für jeden Job. Wenn Sie einen Befehl ausführen, der mehrere Jobs unterstützt, verwendet XCP minimalen Hostspeicher, um den Job abzuschließen, wodurch die Kapazität für die Ausführung zusätzlicher Jobs auf derselben Hostkonfiguration entsteht.



== Mindestsystemanforderungen

Für jeden XCP-Job sollten Sie bis zu 64 GB Hostspeicher und acht Kerne für mittelgroße bis große Migrationen zulassen.


NOTE: Das Ausführen mehrerer XCP-Jobs auf demselben Host wird für die SMB-Datenmigration nicht unterstützt.



== Protokollierung

Standardmäßig wird jeder XCP-Job in einer separaten Protokolldatei protokolliert, die für die Job-ID eindeutig ist. Dieser Protokollierungsmechanismus funktioniert gut, wenn mehrere Jobs auf demselben individuellen Host ausgeführt werden. NetApp empfiehlt keine Änderung des `xcpLogConfig.Json` Datei, um eine einzelne zu verwenden `xcp.log` Datei zum Protokollieren mehrerer XCP-Jobs, die parallel auf demselben Host ausgeführt werden.



== Unterstützte Befehle

Das Ausführen mehrerer XCP-Jobs auf demselben Host wird durch die folgenden XCP-Befehle unterstützt:

* `scan`
* `copy`
* `resume`
* `verify`
* `isync`
* `chmod`
* `chown`
* `delete`




== Nicht unterstützte Befehle

Das Ausführen mehrerer XCP-Jobs auf demselben Host wird von nicht unterstützt `sync` Befehl.
